apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: wisecow-app
  name: wisecow-app
spec:
  ports:
    - name: 5000-5000
      nodePort: 31002
      port: 4499
      protocol: TCP
      targetPort: 4499
  selector:
    app: wisecow-app
  type: NodePort
status:
  loadBalancer: {}
