name: Wisecow-app

on:
  push:
    branches:
      - main

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: csborle/wisecow-app:latest

  deploy-to-kubernetes:
    runs-on: ubuntu-latest
    needs: build-and-push-image
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Create kubeconfig 
        run: |
          mkdir ${HOME}/.kube
          echo "${{ secrets.KUBE_CONFIG }}" | base64 --decode > ${HOME}/.kube/config

      - name: Deploy to Kubernetes
        run: kubectl apply -f deployment.yaml -f service.yaml --validate=false
